In [2]:
# importing libraries
import pandas as pd
import json

# Match Summary

In [86]:
with open(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Jsons\t20_wc_match_results.json') as f:
    data =json.load(f)

#storing the data in dataframe    
df_match =pd.DataFrame(data[0]['matchSummary'])
df_match.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [87]:
df_match.rename({'scorecard':'match_id'},axis=1,inplace=True)
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [91]:
#creating a dictionary for mapping the data from Match summary

match_ids_dict ={}

for index, row in df_match.iterrows():
    key1 = row['team1']+' Vs ' +row['team2']
    key2 = row['team2']+' Vs ' +row['team1']
    match_ids_dict[key1]=row['match_id']
    match_ids_dict[key2]=row['match_id']

In [56]:
df_match.to_csv(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Csv\matches.csv' ,index =False)

# Batting Summary

In [67]:
#loading the file and storing in the dataframe
with open(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Jsons\t20_wc_batting_summary.json') as f:
    data =json.load(f)
all_records =[]
    
for rec in data:
    all_records.extend(rec['battingSummary'])
               
df_batting =pd.DataFrame(all_records)
df_batting.head(20)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c â€ Green b Shikongo,0,1,0,0,0.00
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,2,0,95.23
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),c â€ Green b Frylinck,29,23,2,1,126.08
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,0,0,50.00
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,c Baard b Smit,5,8,0,0,62.50
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,run out (van Lingen/â€ Green),0,0,0,0,-
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,c Erasmus b Wiese,8,15,0,0,53.33
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,,11,11,0,1,100.00
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,c â€ Edwards b van der Merwe,12,20,1,0,60.00

In [68]:
# creating a new column 
df_batting["out/not_out"] =df_batting.dismissal.apply(lambda x: "out" if len(x)>0 else "not_out")
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00,out

In [69]:
#dropping Unnecssary columns
df_batting.drop(columns =['dismissal'],inplace =True)
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out

In [70]:
# cleaning weird symbols from the names
df_batting['batsmanName'] =df_batting['batsmanName'].apply(lambda x: x.replace('â€',''))
df_batting['batsmanName'] =df_batting['batsmanName'].apply(lambda x: x.replace('\xa0',''))
df_batting['batsmanName'] =df_batting['batsmanName'].apply(lambda x: x.replace('(c)',''))
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out

In [53]:
#checking if the match has substrings of team1 and team2

for m in range(len(df_match.team1)):
    for b in range(len(df_batting.match)):
        if (df_match.team1[m] in df_batting.match[b] and df_match.team2[m] in df_batting.match[b]):
            #if both team1 and team2 present in the match store them in df_batting
            df_batting['match_id'][b] =df_match['match_id'][m]

df_batting.tail(20)

C:\Users\subha\AppData\Local\Temp\ipykernel_7932\3750273471.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_batting['match_id'][b] =df_match['match_id'][m]

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
679,India Vs England,India,7,Ravichandran Ashwin,0,0,0,0,-,not_out,T20I # 1878
680,India Vs England,England,1,Jos Buttler,80,49,9,3,163.26,not_out,T20I # 1878
681,India Vs England,England,2,Alex Hales,86,47,4,7,182.97,not_out,T20I # 1878
682,Pakistan Vs England,Pakistan,1,Mohammad Rizwan,15,14,0,1,107.14,out,T20I # 1879
683,Pakistan Vs England,Pakistan,2,Babar Azam,32,28,2,0,114.28,out,T20I # 1879
684,Pakistan Vs England,Pakistan,3,Mohammad Haris,8,12,1,0,66.66,out,T20I # 1879
685,Pakistan Vs England,Pakistan,4,Shan Masood,38,28,2,1,135.71,out,T20I # 1879
686,Pakistan Vs England,Pakistan,5,Iftikhar Ahmed,0,6,0,0,0.00,out,T20I # 1879
687,Pakistan Vs England,Pakistan,6,Shadab Khan,20,14,2,0,142.85,out,T20I # 1879
688,Pakistan Vs England,Pakistan,7,Mohammad Nawaz,5,7,0,0,71.42,out,T20I # 1879
689,Pakistan Vs England,Pakistan,8,Mohammad Wasim,4,8,0,0,50.00,out,T20I # 1879
690,Pakistan Vs England,Pakistan,9,Shaheen Shah Afridi,5,3,1,0,166.66,not_out,T20I # 1879
691,Pakistan Vs England,Pakistan,10,Haris Rauf,1,1,0,0,100.00,not_out,T20I # 1879
692,Pakistan Vs England,England,1,Jos Buttler,26,17,3,1,152.94,out,T20I # 1879
693,Pakistan Vs England,England,2,Alex Hales,1,2,0,0,50.00,out,T20I # 1879
694,Pakistan Vs England,England,3,Phil Salt,10,9,2,0,111.11,out,T20I # 1879
695,Pakistan Vs England,England,4,Ben Stokes,52,49,5,1,106.12,not_out,T20I # 1879
696,Pakistan Vs England,England,5,Harry Brook,20,23,1,0,86.95,out,T20I # 1879
697,Pakistan Vs England,England,6,Moeen Ali,19,13,3,0,146.15,out,T20I # 1879
698,Pakistan Vs England,England,7,Liam Livingstone,1,1,0,0,100.00,not_out,T20I # 1879

In [57]:
df_batting.to_csv(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Csv\batting.csv',index =False)

# Bowling Summary

In [89]:
with open(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Jsons\t20_wc_bowling_summary.json') as f:
    data =json.load(f)
all_records =[]
    
for rec in data:
    all_records.extend(rec['bowlingSummary'])
               
df_bowling =pd.DataFrame(all_records)
print(df_bowling.shape)
df_bowling.head(20)

(500, 13)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0
10,Namibia Vs Sri Lanka,Namibia,Jan Frylinck,4,0,26,2,6.50,10,0,2,1,0
11,U.A.E. Vs Netherlands,Netherlands,Fred Klaassen,4,0,13,2,3.25,18,0,0,3,0
12,U.A.E. Vs Netherlands,Netherlands,Tim Pringle,4,0,13,1,3.25,11,0,0,0,0
13,U.A.E. Vs Netherlands,Netherlands,Logan van Beek,2,0,19,0,9.50,5,0,2,1,0
14,U.A.E. Vs Netherlands,Netherlands,Bas de Leede,3,0,19,3,6.33,9,2,0,2,0
15,U.A.E. Vs Netherlands,Netherlands,Paul van Meekeren,4,0,21,0,5.25,11,1,0,0,0
16,U.A.E. Vs Netherlands,Netherlands,Roelof van der Merwe,3,0,19,1,6.33,7,0,1,0,0
17,U.A.E. Vs Netherlands,U.A.E.,Junaid Siddique,4,0,24,3,6.00,10,2,0,1,0
18,U.A.E. Vs Netherlands,U.A.E.,Basil Hameed,1,0,7,1,7.00,4,0,1,0,0
19,U.A.E. Vs Netherlands,U.A.E.,Aayan Afzal Khan,3,0,15,1,5.00,8,1,0,0,0

In [92]:
#appending match_id Column to the df_bowling
df_bowling['match_id'] =df_bowling['match'].map(match_ids_dict)

df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823

In [93]:
#saving into the file
df_bowling.to_csv(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Csv\bowling.csv',index =False)

# Player Information

In [99]:
with open(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Jsons\t20_wc_player_info.json') as f:
    data =json.load(f)

df_players =pd.DataFrame(data)
df_players.head(20)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendisâ€,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka(c),Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,

In [100]:
# cleaning weird symbols from the names
df_players['name'] =df_players['name'].apply(lambda x: x.replace('â€',''))
df_players['name'] =df_players['name'].apply(lambda x: x.replace('\xa0',''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('†', ''))
df_players['name'] =df_players['name'].apply(lambda x: x.replace('(c)',''))
df_players.head(20)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka,Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,

In [102]:
df_players.to_csv(r'D:\Data Analyst Portfolio\_Projects\Power BI T20 2022 Project\Csv\Player_info_no_img.csv',index =False)

In [108]:
#indian players in 2022 T20 WC

df_players[df_players.team=='India']

,name,team,battingStyle,bowlingStyle,playingRole,description
127,KL Rahul,India,Right hand Bat,,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
128,Rohit Sharma,India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
129,Virat Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
130,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
131,Axar Patel,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
132,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
133,Dinesh Karthik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
134,Ravichandran Ashwin,India,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
135,Bhuvneshwar Kumar,India,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
136,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,
137,Mohammed Shami,India,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."